### ISSUE TITLE
Compiling for iOS9

### ISSUE THREAD

**Issue by rickbarnsley** [libretro/gw-libretro#11]
I'm trying to build this core for use on an iPhone running iOS 9.2, however running the script as-is won't generate an iOS9 compatible dynamic library, and when I try to hack the script to use the right parameters I start getting warnings about the cpp libraries in the src folder missing the armv7 architecture. Is there any chance you could update the makefile so that we can compile for iOS9 ?

**Comment by leiradel** [comment]
Hi @rickbarnsley, sorry for taking so long to answer...

You can download a pre-compiled gw-libretro core from within RetroArch using the Core Updater. If you really need to compile the core by yourself, I've been told that the following works:

    make platform=ios9

but I don't have a Mac to test.

Please let me know if that was helpful so I can close this issue.

**Comment by rickbarnsley** [comment]
Hi @leiradel, no problem... thanks so much for getting back to me. 

I managed to get this built with that command, codesigned then verified it works on iOS9.2.

For completeness I couldn't find the pre-compiled gw-libretro core from within the RetroArch Core Updater... do you know what exactly is it listed as?

**Comment by leiradel** [comment]
On Windows, I've seen it listed as gw_libretro.dll.zip and Game & Watch.
