### ISSUE TITLE
lr-gw crashes with Segmentation fault on Pi Zero

### ISSUE THREAD

**Issue by mrvanes** [libretro/gw-libretro#13]
This is the output from runcommand:

/tmp $ cat runcommand.log 
filestream_read_file: Failed to open /home/pi/RetroPie/roms/gameandwatch/Parachute.srm: No such file or directory
/opt/retropie/supplementary/runcommand/runcommand.sh: line 804:  1644 Segmentation fault      /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-gw/gw_libretro.so --config /opt/retropie/configs/gameandwatch/retroarch.cfg "/home/pi/RetroPie/roms/gameandwatch/Parachute.mgw" --appendconfig /tmp/retroarch.cfg

**Comment by leiradel** [comment]
I believe the front-end, RetroArch in this case, is at fault here. gw-libretro doesn't even use the `filestream_read_file` function.

**Comment by mrvanes** [comment]
I read the first line only as a warning (the game has no .srm file in the zip) and suspected gw_libretro.so to be the culprit of the segfault nevertheless? You don't think so?

**Comment by leiradel** [comment]
You're right, that line could be just a warning, but to find the culprit we'll need a stack trace. Are you able to run that command via gdb using debug builds of RetroArch and gw-libretro?

**Comment by mrvanes** [comment]
Surely not before I leave for holiday... was hoping someone could reproduce :/
