### ISSUE TITLE
Donkey Kong Jr. (Zoom)

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#17]
Donkey Kong Jr. _(Nintendo, Panorama Screen)_
Press `SELECT` to play the game in zoomed mode.
Uh-oh. It does not look right. Things got cut off. 

![dk-box](https://cloud.githubusercontent.com/assets/852504/21078831/0b4ee882-bf43-11e6-8d6c-18a42ab676d8.png)

**Comment by leiradel** [comment]
The fixed game is available for download at the [buildbot](http://buildbot.libretro.com/assets/cores/Game%20and%20Watch/Donkey%20Kong%20Jr.%20%28Nintendo%20Panorama%20Screen%29.zip).

Thanks for the report.

**Comment by lasers** [comment]
Fix confirmed. Thank you for fixing it. 👍
