### ISSUE TITLE
Hot Line (VTech, Sporty Time & Fun) (Zoom)

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#19]
Hot Line _(VTech, Sporty Time & Fun)_
Press `SELECT` to play the game in zoomed mode.
Uh-oh. It does not look right. Things got cut off.

![hlb](https://cloud.githubusercontent.com/assets/852504/21083222/698cda4e-bfb1-11e6-9dac-9d3d7205996e.png)

The left image should be fixed too.

**Comment by leiradel** [comment]
Fixed
