### ISSUE TITLE
Mickey Mouse (Panorama Screen) (Zoom)

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#21]
Mickey Mouse _(Panorama Screen)_
Press `SELECT` to play the game in zoomed mode.
Uh-oh. It does not look right. Things got cut off.

![mmb](https://cloud.githubusercontent.com/assets/852504/21083648/9fcd7330-bfba-11e6-8c3e-b2e41ff78b86.png)

**Comment by leiradel** [comment]
Fixed.
