### ISSUE TITLE
Sleep Walker (VTech, Time & Fun) (Background)

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#22]
Sleep Walker _(VTech, Time & Fun)_
Press `(nothing)` to view the handheld in normal mode.
Uh-oh. It does not look right. Things got non-consistent.

![sleep walker vtech time _ fun](https://cloud.githubusercontent.com/assets/852504/21083774/7a3d69d8-bfbd-11e6-9c8a-9a348f9cecf0.png)

The background should be black, not white.

**Comment by leiradel** [comment]
Hm... Fixed?
