### ISSUE TITLE
Snoopy (Nintendo, Panorama Screen) (Zoom)

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#23]
Snoopy _(Nintendo, Panorama Screen)_
Press `SELECT` to play the game in zoomed mode.
Uh-oh. It does not look right. Things got cut off.

![snoopy-b](https://cloud.githubusercontent.com/assets/852504/21083812/1afe6944-bfbe-11e6-933d-96e7d3fb91f4.png)

**Comment by leiradel** [comment]
Fixed. The background has the correct color now too.
