### ISSUE TITLE
Snoopy Tennis (Nintendo, Wide Screen) (Shadow)

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#24]
Snoopy Tennis _(Nintendo, Wide Screen)_
Press (nothing) to view the game in normal mode.
Uh-oh. It does not look right. Things got really distracting.

![snoopytennis-b](https://cloud.githubusercontent.com/assets/852504/21083901/9f3930da-bfbf-11e6-92c2-a0a109a1a31a.png)

This is questionable. The thick shadow edges on left/top.

**Comment by leiradel** [comment]
Can't fix :(
