### ISSUE TITLE
Sub Chase (Mattel Electronics) (Zoom)

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#25]
Sub Chase _(Mattel Electronics)_
Press `SELECT` to play the game in zoomed mode.
Uh-oh. It does not look right. Things got cut off.

![sc-b](https://cloud.githubusercontent.com/assets/852504/21083946/7ad30314-bfc0-11e6-9e71-7da00e5e9022.png)

This is questionable.

**Comment by leiradel** [comment]
Fixed
