### ISSUE TITLE
Towering Rescue (Gakken, LCD Card Game) (Shadow)

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#26]
Towering Rescue _(Gakken, LCD Card Game)_
Press `(nothing)/SELECT` to view the game in normal/zoomed mode.
Uh-oh. It does not look right. Things can really distracting.

![tr-b](https://cloud.githubusercontent.com/assets/852504/21084032/29dc35e6-bfc2-11e6-91b9-2f8c2fba7e4d.png)

This is questionable. The thick shadow on top.

**Comment by leiradel** [comment]
Unfortunately, the game scans have these shadows, so unless we find a graphic artist who manages to edit the images and remove these shadows, there's nothing I can do.

I'll close this issue and other similar issues. If we come to find an artist, I'll check with the author if I can share some selected images to get the shadows removed.

**Comment by lasers** [comment]
Where did game scans came from? If it's from your friend, he/she could try buying a $10~ jeweler's loupe (10x?) to be used with their smartphone or Amazon "iphone lens" to make better game scans... along with plenty of lights (at least 3).

http://i.imgur.com/SCsG11V.jpg
http://i.imgur.com/qvNtfFi.jpg
http://i.imgur.com/GoioxG5.jpg

If you looked at game snaps closely, some game scans are much darker than others. I think this jewelry's loupe / iphone lens thing might be easier (and genuine) than finding a graphic artist to clean up the shadows.

Also, I'm not sure why this Towering Rescue LCD Card Game device have weird light pattern. It looks like the light source came through vertical blinds or LED dots shining nearby. All this would mean more works for somebody so meh... Nothing should be okay.

**Comment by leiradel** [comment]
> Where did game scans came from? If it's from your friend, he/she could try buying a $10~ jeweler's loupe (10x?) to be used with their smartphone or Amazon "iphone lens" to make better game scans... along with plenty of lights (at least 3).

He doesn't own all those games, so he receives scans from people who actually own the ones he misses, and not everyone knows how to do it correctly. Some people may try multiple times, others send bad scans and call it a day.
