### ISSUE TITLE
Donkey Kong Jr. (Nintendo, Table Top) (Zoom)

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#27]
Donkey Kong Jr. (Nintendo, Table Top)
Press `SELECT` to play the game in zoomed mode.
Uh-oh. It does not look right. Things got cut off.

![donkey kong jr nintendo table top -b](https://cloud.githubusercontent.com/assets/852504/21084392/91780c88-bfc8-11e6-8d8e-e1016e98ab80.png)

I forget this one.

**Comment by leiradel** [comment]
Fixed in the last update
