### ISSUE TITLE
Handheld Electronic Game

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#28]
Hi. You got your new thumbnails. All 56 verified to be in working condition.
- Some boxarts are too big/tall.
- Some snaps are dark or contain thick shadow edges.
- Some snaps are cut off. I can update them after you fixed them.

You got your new issues. All verified in RetroArch to be confirmed bugs.
- 11 or 12 issues in a day.
- World record for gw-libretro. Dec 11, 2016.

Can you sanitize the filenames by replacing all `&` with `_`? 
Link: https://buildbot.libretro.com/assets/cores/Game%20and%20Watch/
- Some systems could have problem downloading them.
- To stay in naming consistent with other games, the newest Donkey Kong Jr mgw you pushed out yesterday is missing a comma. Sorry about nitpicking.
- Rename `Game and Watch` directory to `Handheld Electronic Game`

Other than everything listed above, I think this is last thing for you to do.

Replace `Game & Watch` with `Handheld Electronic`

	./src/libretro.c:173:  info->library_name = "Game & Watch";

The core will be `Handheld Electronic (GW)` to load any `Handheld Electronic Game` game.

There are `Game & Watch` in READ.md that you can replace with either `Handheld Electronic` or `Handheld Electronic Game`... Whatever suits you.

	./README.md:3:**gw-libretro** is a [libretro](http://www.libretro.com/) core that runs Game & Watch simulators.
	./gwlua/README.md:3:A middleware to write Game & Watch-like games in...
	./gwlua/README.md:15:When I started porting [MADrigal](http://www.madrigaldesign.it/sim/)'s Game & Watch simulators to...

I hope everything has been to your satisfaction. Cheers. 

EDIT: And `./rules.d/core-rules.sh:668:libretro_gw_name="Game & Watch"` in super.

**Comment by leiradel** [comment]
> Some boxarts are too big/tall.

These will have to be resized.

> Some snaps are dark or contain thick shadow edges.

These will need editing in the images (I already got an ok from MADrigal to pass the images to someone willing to make them better.)

> Some snaps are cut off. I can update them after you fixed them.

These will have to wait for the bug fixes.

> World record for gw-libretro. Dec 11, 2016.

Good job, I appreciate.

> Can you sanitize the filenames by replacing all & with _?

I'll check what is the current policy regarding path sanitation.

> Replace Game & Watch with Handheld Electronic

Will do in a couple of weeks.

**Comment by leiradel** [comment]
I believe the thumbnails are in place, so I'm close this issue. Thanks for your work!
