### ISSUE TITLE
What happened with the Handheld Electronic (GW) core in RetroArch?

### ISSUE THREAD

**Issue by LukasThyWalls** [libretro/gw-libretro#39]
In the last week of 2017 i installed RetroArch with the Handheld Electronic (GW) via it's online updater in two Android (Tablet and Phone), but few days ago i reinstalled RetroArch in my phone but the GW core is not there anymore.

I tried the 1.7.0 and 1.7.0 (via F-Droid repository) and 1.7.0 via Google Play, and there isn't the GW Core. In the tablet i have the GW core installed, but when RetroArch download the core list updates there isn't the GW Core in the list.

I didn't found any reference or statement about this and seeing the RetroArch issue tracker seems here where to question that.

**Comment by twinaphex** [comment]
I mentioned it to @leiradel. It is out of my hands at least.

**Comment by leiradel** [comment]
The core is failing to build for Android, but I don't know why the last working version is missing from the updater.

**Comment by PanosPl** [comment]
I saw some commits and the core is back at Latest and I updated the core in my Android phone(v7a version). It does not seem to work. Game A, B etc do not trigger using the on screen buttons.

**Comment by leiradel** [comment]
@PanosPl you mean by touching them?

**Comment by PanosPl** [comment]
Yes. I can see the on-screen buttons but pressing them does not do anything EXCEPT the Dpad and the 4 "fire" buttons.

**Comment by leiradel** [comment]
@PanosPl Which game were you testing?

**Comment by PanosPl** [comment]
@leiradel Parachute

**Comment by LukasThyWalls** [comment]
Two days ago i realized that the Handheld Electronic (GW) core is there again (with a bunch cores more) and i downloaded it. Yesterday i updated and tested it with Madrigal's Donkey Kong I and Donkey Kong II, and like reported thing above, the Game A, Game B, Reset, etc are not pushed (Virtual L1, R2, R1 buttons before) and to press to use them i need to use the virtual Select and Start button.

Before that i realized too the games are too slow, unplayable. Feels like you have to push buttons to happen anything, meanwhile seems freeze but they really are not.

Maybe this should be opened as new issue in the bug tracker.

**Comment by leiradel** [comment]
I'm closing this since the Android core is back. Please report other issues separately.
