### ISSUE TITLE
where is the android build gw-core?

### ISSUE THREAD

**Issue by duskgao** [libretro/gw-libretro#4]
I can't find the android gw-libretro core in the retroarch buildbot...anything I missed?

**Comment by leiradel** [comment]
The buildbot is having trouble building gw-libretro, were working on a fix.

**Comment by duskgao** [comment]
Many THX for your HARD work!! :D @leiradel

**Comment by leiradel** [comment]
Thanks! :)

I've committed a fix, the buildbot should rebuild in about 12 hours from now. I'll leave the issue open until the fix can be validated.

**Comment by leiradel** [comment]
The buildbot is successfully generating the gw cores for android now.
