### ISSUE TITLE
Both multiscreen Donkey Kongs don't play

### ISSUE THREAD

**Issue by mrvanes** [libretro/gw-libretro#42]
I have several games that play correctly on lr-gw on my Odroid-XU4 (big.LITTLE armv7) but both Nintendo Multiscreen Donkey Kongs (I & II) stop after first jump or somewhere near the first jump action. DK II can be tricked into action by jumping (it's as if each jump makes the clock tick) where as DK I completely stops after first jump.

I've downloaded the latest game builds yesterday. The ones that use select to travel between the buttons, instead of selecting game A or B using L/R (which also didn't work)

**Comment by danryu** [comment]
+1 on this
Running Retropie on a Raspberry Pi 3B+, latest builds of OS/ES/libretro.

The original Donkey Kong multiscreen was the main one I wanted to get work too, it was the only one I actually physically owned...

**Comment by leiradel** [comment]
I've just updated both games [here](http://buildbot.libretro.com/assets/cores/Handheld%20Electronic%20Game/), can you guys test them? Thanks

**Comment by mrvanes** [comment]
They both work like a charm now. Thx!
Although there's one tiny thing: I remember the d-pad to repeat when pressed longer, but that doesn't seem to be implemented. Either because my 8bitdo doesn't send repeats or the rom doesn't support it?

**Comment by leiradel** [comment]
Button repeats was a feature of the ROM. Why do you miss it? Does it affect gameplay?

**Comment by mrvanes** [comment]
My muscle-memory misses it so it affects the way my thumbs remember playing the game ;)

**Comment by danryu** [comment]
Both tested and working here, thanks @leiradel

**Comment by leiradel** [comment]
> My muscle-memory misses it so it affects the way my thumbs remember playing the game ;)

I'll see if I can simulate the same behavior.
