### ISSUE TITLE
Request for permission - GW Free DLC for RetroArch on Steam

### ISSUE THREAD

**Issue by twinaphex** [libretro/gw-libretro#59]
Hi there @leiradel,

We would like to seek your permission to include GW Libretro as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

PS. I've already contacted Madrigal, this is what he said -

'I am not the author of the Retroarch version of the games. Andre Leiradella is the author of the gw-libretro core and the games. I am the author of the original game source codes, and I granted him permission to port them to libretro
Please speak to him. His contact details are on the gw-libretro documentation'

**Comment by leiradel** [comment]
Sure, no problems from me. Other than Lua and `libretro.h` I'm the only author. There were some pull requests but I think none of them changed the code.

As for the games, they are freely available, just notice that they contain images of actual handheld devices, so I'm not sure about rights in distributing them, not even by me or MADrigal.

**Comment by twinaphex** [comment]
Thanks.

Yeah, we would likely not be distributing any actual data files themselves, that is an exercise left up to the user.
