### ISSUE TITLE
Zoom function broken on several GW games in RA 1.16 Android 

### ISSUE THREAD

**Issue by TurboFrost** [libretro/gw-libretro#74]
Using the Android version of the latest stable build of Retro Arch, when playing some games such as Snoopy Tennis widescreen, the zoom function, the screen is overstretched and not visible.  I have verified the same with a few more games such as Sleepwalker,safari and many others.

Not sure if this is a retro arch issue or the core not playing well with the latest stable and nightly build.

**Comment by leiradel** [comment]
The last code change in this core was on April/2022, so this must be an issue with RetroArch.

**Comment by TurboFrost** [comment]
I think I found the issue and resolved it.  RetroArch defaults the video output to GL but when I changed it to Vulkan, the Zoom function works normally.  To fix this all you need to do is load a game, go to the main configuration and change the video output to vulkan.  Then go back to the core menu and save it as a core override.  Moving forward the core will always default to vulkan when loaded.  Hope this resolves it for everyone that runs into this zoom issue.
